apiVersion: v1
kind: Service
metadata:
  name: svc-geoserver
  namespace: ns-sigemad
spec:
  selector:
    app: geoserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # <-- Puedes elegir otro puerto entre 30000-32767
