apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sigemad-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DS-Miri/test-manifiestos'
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

